import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/shared/Header";
import  LoadingProvider from "./context/LoadingContext";
import GlobalLoading from "./components/shared/GlobalLoading";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Gestão de Gueltas - M|Q",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="bg-black text-white">
      <LoadingProvider>
      <GlobalLoading />
        <Header />
          {/* 🔹 Cabeçalho Fixo */}
          {children}
      </LoadingProvider>
      </body>

    </html>
  );
}
